---Optimización del SP SEL_TAR_SP 26/01/2017

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [_dta_index_Tar_7_789577851__K7_1_3_8] ON [dbo].[Tar]
(
	[numTAR] ASC
)
INCLUDE ( 	[idTAR],
	[TAR],
	[idZona]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
