 module.exports = {
     cita: require('./controllers/cita'),
     cotizacion: require('./controllers/cotizacion'),
     trabajo: require('./controllers/trabajo'),
     orden: require('./controllers/ordenes'),
     login: require('./controllers/login'),
     example: require('./controllers/example'),
     reporte: require('./controllers/reporte'),
     osur: require('./controllers/osur'),
     taller: require('./controllers/taller'),
     ordenAnticipo: require('./controllers/ordenAnticipo'),
     dashboard: require('./controllers/dashboard'),
     administracion: require('./controllers/administracion'),
     reclamacion: require('./controllers/reclamacion'),
 }